CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  image VARCHAR(255),
  sold TINYINT(1) DEFAULT 0,
  visible TINYINT(1) DEFAULT 1
);
